
package GUI;

import System.MainServer;
import System.Client;

import javax.sound.sampled.Port;
import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.util.ArrayList;

/**
 *
 * @author maher
 */
public class LOGIN extends javax.swing.JFrame {

    /**
     * Creates new form LOGIN
     */
    public LOGIN() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        JoinBtn = new javax.swing.JButton();
        UsernameTextfield = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        AddServerBtn = new javax.swing.JButton();
        PortArea = new javax.swing.JTextField();
        ServersList = new javax.swing.JList();
        ConnectBtn = new javax.swing.JButton();
        model = new DefaultListModel<MainServer>();
        ServersList.setModel(model);
        ServersList.setFont(new java.awt.Font("Ubuntu", 0, 36));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(230, 251, 254));
        jPanel1.setPreferredSize(new java.awt.Dimension(701, 1200));

        JoinBtn.setFont(new java.awt.Font("Ubuntu", 0, 36)); // NOI18N
        JoinBtn.setText("Join");
        JoinBtn.setToolTipText("");
        JoinBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JoinBtnActionPerformed(evt);
            }
        });

        UsernameTextfield.setFont(new java.awt.Font("Ubuntu", 0, 36)); // NOI18N
        UsernameTextfield.setText("  ex: Maher");

        jLabel1.setFont(new java.awt.Font("Ubuntu", 0, 36)); // NOI18N
        jLabel1.setText("Enter Your Username :");

        jLabel2.setFont(new java.awt.Font("Ubuntu", 0, 36)); // NOI18N
        jLabel2.setText("Choose a Server  :");

        AddServerBtn.setFont(new java.awt.Font("Ubuntu", 0, 30)); // NOI18N
        AddServerBtn.setText("Add Server");
        AddServerBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                try {
                    AddServerBtnActionPerformed(evt);
                } catch (Exception e) {
                    System.out.println("1 "+ e.getMessage());
                }
            }
        });

        PortArea.setFont(new java.awt.Font("Ubuntu", 0, 36)); // NOI18N
        PortArea.setText("Port");
        PortArea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PortAreaActionPerformed(evt);
            }
        });

        ConnectBtn.setFont(new java.awt.Font("Ubuntu", 0, 36)); // NOI18N
        ConnectBtn.setText("Connect");
        ConnectBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                try {
                    ConnectBtnActionPerformed(evt);
                } catch (Exception e) {
                    System.out.println("2 "+ e.getMessage());
                }
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(PortArea, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(AddServerBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 291, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(ServersList, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ConnectBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(182, 182, 182)
                                .addComponent(JoinBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(182, 182, 182))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 275, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(UsernameTextfield))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PortArea)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(AddServerBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ServersList, javax.swing.GroupLayout.PREFERRED_SIZE, 704, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ConnectBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(UsernameTextfield, javax.swing.GroupLayout.DEFAULT_SIZE, 69, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(JoinBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 69, Short.MAX_VALUE)
                .addGap(86, 86, 86))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 730, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JoinBtnActionPerformed(ActionEvent evt) {
        Object[] selected = ServersList.getSelectedValues();
        if(selected.length!= 1){
            JOptionPane.showMessageDialog(null, "Please select EXACLY 1 Server", "Error", JOptionPane.INFORMATION_MESSAGE);

        }
        else{
            MainServer server = (MainServer) selected[0];
            String name = UsernameTextfield.getText();
            try {
                Client c = new Client(server.getPort(), name);
                //App app = new App(c);
            } catch (Exception e) {
                System.out.println("3 "+ e.getMessage());
            }
        }
    }

    private void ConnectBtnActionPerformed(java.awt.event.ActionEvent evt) throws Exception {
        Object [] selected = ServersList.getSelectedValues();
        if(selected.length != 2){
            JOptionPane.showMessageDialog(null, "Please select EXACLY 2 Servers", "Error", JOptionPane.INFORMATION_MESSAGE);
        }
        else{
            MainServer server1 =(MainServer) selected[0];
            MainServer server2 =(MainServer) selected[1];
            server1.connectToServer(server2.getPort());
        }

    }
    //Done
    private void AddServerBtnActionPerformed(java.awt.event.ActionEvent evt) throws Exception {                                             
        String port = PortArea.getText();
        int portnum ;
        try{
            portnum = Integer.parseInt(port);
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, "Please enter a number", "Error", JOptionPane.INFORMATION_MESSAGE);
            System.out.println(e.getMessage());
            return;
        }
        MainServer server = new MainServer(portnum);
        Servers.add(server);
        model.addElement(server);
        Serverno++;


    }


    private void PortAreaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PortAreaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PortAreaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws Exception{
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LOGIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LOGIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LOGIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LOGIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LOGIN().setVisible(true);
            }
        });

    }


    private ArrayList<MainServer> Servers = new ArrayList<MainServer>();
    private int Serverno;
    private DefaultListModel<MainServer> model;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddServerBtn;
    private javax.swing.JButton ConnectBtn;
    private javax.swing.JButton JoinBtn;
    private javax.swing.JTextField PortArea;
    private javax.swing.JList ServersList;
    private javax.swing.JTextField UsernameTextfield;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
